# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESSUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100)),
                ('isresovled', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='POINT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=50)),
                ('point_map', models.IntegerField()),
                ('point_position_x', models.IntegerField()),
                ('point_position_y', models.IntegerField()),
                ('instrument', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='essue',
            name='point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.POINT'),
        ),
        migrations.AddField(
            model_name='essue',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.USER'),
        ),
    ]
