# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='computername',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.USER'),
            preserve_default=False,
        ),
    ]
