# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170504_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essue',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='user_id',
            new_name='user',
        ),
    ]
