# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20170504_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.CharField(default='Idle', max_length=50),
        ),
    ]
