# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_point_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essue',
            old_name='point_id',
            new_name='point',
        ),
    ]
