# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20170417_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='essue',
            name='title',
            field=models.CharField(default='null', max_length=16),
            preserve_default=False,
        ),
    ]
