# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_point_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='ip',
            field=models.CharField(default='181.1.0.0', max_length=50),
            preserve_default=False,
        ),
    ]
