# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
