# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.IntegerField()),
                ('image_filepath', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KNOWLEDGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('content', ckeditor.fields.RichTextField()),
                ('create_time', models.DateTimeField()),
                ('lastedit_time', models.DateTimeField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.GRADE')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.USER')),
            ],
        ),
    ]
