# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
