# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20170425_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='lastedit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
